// This file was automatically generated by sk-code-generator.py
// DO NOT MODIFY! YOUR CHANGES WOULD BE OVERWRITTEN
// Look at ./src/common/signalk/SKPathToString.cpp.tmpl instead or modify the script
// Generated on 2017-09-11 11:34:19.472636

#include "SKPath.h"

String SKPath::toString() const {
  String path;

  switch (_p) {
    case SKPathEnvironmentOutsidePressure:
      path = "environment.outside.pressure";
      break;
    case SKPathElectricalBatteriesVoltage:
      path = "electrical.batteries." + _index + ".voltage";
      break;
    case SKPathNavigationAttitude:
      path = "navigation.attitude";
      break;
    case SKPathNavigationCourseOverGroundTrue:
      path = "navigation.courseOverGroundTrue";
      break;
    case SKPathNavigationHeadingMagnetic:
      path = "navigation.headingMagnetic";
      break;
    case SKPathNavigationPosition:
      path = "navigation.position";
      break;
    case SKPathNavigationSpeedOverGround:
      path = "navigation.speedOverGround";
      break;
    case SKPathNavigationSpeedThroughWater:
      path = "navigation.speedThroughWater";
      break;
    case SKPathEnvironmentDepthBelowKeel:
      path = "environment.depth.belowKeel";
      break;
    case SKPathEnvironmentDepthBelowTransducer:
      path = "environment.depth.belowTransducer";
      break;
    case SKPathEnvironmentDepthBelowSurface:
      path = "environment.depth.belowSurface";
      break;
    case SKPathEnvironmentDepthTransducerToKeel:
      path = "environment.depth.transducerToKeel";
      break;
    case SKPathEnvironmentDepthSurfaceToTransducer:
      path = "environment.depth.surfaceToTransducer";
      break;

    case SKPathInvalidPath:
    case SKPathEnumIndexedPaths:
      path = "invalid";
      break;
  }

  return path;
};

