// This file was automatically generated by sk-code-generator.py
// DO NOT MODIFY! YOUR CHANGES WOULD BE OVERWRITTEN
// Look at SKPathEnum.h.tmpl instead or modify the script
// Generated on 2017-11-26 18:40:04.702807

typedef enum {
  SKPathInvalidPath,

  SKPathEnvironmentDepthBelowKeel,
  SKPathEnvironmentDepthBelowTransducer,
  SKPathEnvironmentDepthBelowSurface,
  SKPathEnvironmentDepthTransducerToKeel,
  SKPathEnvironmentDepthSurfaceToTransducer,
  SKPathEnvironmentWaterTemperature,
  SKPathEnvironmentWind,
  SKPathEnvironmentWindAngleApparent,
  SKPathEnvironmentWindAngleTrue,
  SKPathEnvironmentWindDirectionTrue,
  SKPathEnvironmentWindDirectionMagnetic,
  SKPathEnvironmentWindSpeedTrue,
  SKPathEnvironmentWindSpeedOverGround,
  SKPathEnvironmentWindSpeedApparent,
  SKPathEnvironmentOutsidePressure,
  SKPathNavigationAttitude,
  SKPathNavigationCourseOverGroundTrue,
  SKPathNavigationHeadingMagnetic,
  SKPathNavigationLog,
  SKPathNavigationMagneticVariation,
  SKPathNavigationPosition,
  SKPathNavigationSpeedOverGround,
  SKPathNavigationSpeedThroughWater,
  SKPathNavigationTripLog,
  SKPathSteeringRudderAngle,

  // Marker value - Every path below requires an index.
  SKPathEnumIndexedPaths,

  SKPathElectricalBatteriesVoltage,

} SKPathEnum;
