// This file was automatically generated by sk-code-generator.py
// DO NOT MODIFY! YOUR CHANGES WOULD BE OVERWRITTEN
// Look at SKPathEnum.h.tmpl instead or modify the script
// Generated on 2017-11-29 13:58:43.982087

typedef enum {
  SKPathInvalidPath,

  SKPathEnvironmentDepthBelowKeel,
  SKPathEnvironmentDepthBelowTransducer,
  SKPathEnvironmentDepthBelowSurface,
  SKPathEnvironmentDepthTransducerToKeel,
  SKPathEnvironmentDepthSurfaceToTransducer,
  SKPathEnvironmentWaterTemperature,
  SKPathEnvironmentOutsideApparentWindChillTemperature,
  SKPathEnvironmentOutsidePressure,
  SKPathEnvironmentWindAngleApparent,
  SKPathEnvironmentWindAngleTrueGround,
  SKPathEnvironmentWindAngleTrueWater,
  SKPathEnvironmentWindDirectionTrue,
  SKPathEnvironmentWindDirectionMagnetic,
  SKPathEnvironmentWindSpeedTrue,
  SKPathEnvironmentWindSpeedOverGround,
  SKPathEnvironmentWindSpeedApparent,
  SKPathNavigationAttitude,
  SKPathNavigationCourseOverGroundTrue,
  SKPathNavigationHeadingMagnetic,
  SKPathNavigationHeadingTrue,
  SKPathNavigationLog,
  SKPathNavigationMagneticVariation,
  SKPathNavigationPosition,
  SKPathNavigationSpeedOverGround,
  SKPathNavigationSpeedThroughWater,
  SKPathNavigationTripLog,
  SKPathSteeringRudderAngle,
  SKPathSteeringRudderAngleTarget,

  // Marker value - Every path below requires an index.
  SKPathEnumIndexedPaths,

  SKPathElectricalBatteriesVoltage,

} SKPathEnum;
